language: python
python:
  - "3.5"
  - "3.6"
  - 3.7-dev
install:
  - pip install flask "pytest>=4.3" pytest-cov codecov
script:
  - python -m pytest --cov flask_compressed
after_success:
  - codecov
